config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations', sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'items#index'
  resources :items do
    resources :comments, only: :create
    resources :favorites, only: [:create, :destroy]

    collection do
      get 'category/get_category_children', to: 'items#get_category_children', defaults: { format: 'json' }
      get 'list'
      get 'search'
      get 'detail_search'
    end
    member do
      get 'purchase'
      post 'pay'
    end
  end

  resources :users do
    member do #idを指定して特定のページにいく必要がある
      get 'exhibitedShow'
      get 'purchaseGoods'
      get 'commentGoods'
      get 'favoriteGoods'
    end
    collection do #idを指定して特定のページにいく必要がない
      get 'setUpShow'
      get 'information'
    end
  end

  resources :addresses, only: [:new, :create, :edit, :update]
  resources :credit_cards, only:[:index, :new, :create, :destroy, :show]
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
  belongs_to :user
end

app/controllers/credit_cards_controller.rb
class CreditCardsController < ApplicationController
  require "payjp"

  def new
    
  end

  def create
    Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
    if params['payjp-token'].blank?
      redirect_to action: "new" # トークンが取得出来てなければループ
    else
      user_id = current_user.id
      customer = Payjp::Customer.create(
      card: params['payjp-token']
      # params['payjp-token']（response.id）からcustomerを作成
      ) 
      @card = CreditCard.new(user_id: user_id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to user_path(:id), notice: "Credit card registration completed！"
      else
        redirect_to action: "new"
      end
    end
  end
  

  def show #Cardのデータpayjpに送り情報を取り出します
    @card = CreditCard.where(user_id: current_user.id).first
    if @card.blank?
      flash[:notice] = "Please credit card registration！"
      redirect_to action: "new"
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @default_card_information = customer.cards.retrieve(@card.card_id)
    end
  end
  
  
  def destroy 
    @card = CreditCard.find_by(user_id: current_user.id)
    if @card.blank?
      redirect_to action: "show"
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(@card.customer_id)
      customer.delete
      @card.delete
      if @card.destroy
        redirect_to user_path(:id), notice: "Credit card has been deleted!"
      else
        redirect_to action: "show"
      end
    end
  end


end

app/helpers/credit_cards_helper.rb
module CreditCardsHelper
end

app/views/credit_cards/_flash-messages.html.haml
- if flash[:notice]
  %p.flashMge
    = flash[:notice]

- if flash[:alert]
  %p.flashMge
    = flash[:alert]

app/views/credit_cards/_footer-bottom.html.haml
.footer-bottom
  %ul.listTerms
    %li.listTerms__rules
      %a.listTerms__rules--links{:href => "＃"} 利用規約
    %li.listTerms__rules
      %a.listTerms__rules--link{:href => "＃"} プライバシーポリシー
    %li.listTerms__rules
      %a.listTerms__rules--link{:href => "＃"} 特定商取引に関する表記
    %li.listTerms__rules
      %a.listTerms__rules--link{:href => "＃"} 運営会社

app/views/credit_cards/_header-top.html.haml
.contents__top
  .top-title
    %p Rider’s Garage
  .top-text 
    %p アプリをダウンロードして、バイクパーツ・ウェアを売買しよう。
.contents__header
  .header--box
  .header--logo
    = link_to root_path, class: "logo-link" do
      =image_tag(asset_path('14309.gif'), width:"360", height:"180",class: "logo-pte")
      %p.logo-name Rider’s Garage
      %p.logo-text フリマアプリ&サイト Rider’s Garage[ライダースーガレッジ]
  .header--search
    .search-box
      = form_with(url: search_items_path, local: true, method: :get, class: "search-form") do |f|
        = f.text_field :keyword, placeholder: "検索する", class: "search-input"
        %label{for: "search-icon", class: "search-label"}
          %i.fas.fa-search
        .search-icon
          = f.submit "検索", class: "search-btn", id: "search-icon"
    .login
      - if user_signed_in?
        .adjustment-box
        .bottom-box_notice
          %a{:href => "#", class: "bottom-btn"}
            %i.far.fa-bell#bell
          = link_to "お知らせ", information_users_path, class: "bottom-box_notice--btn", id: "search"
        .bottom-box_my-page
          %a{:href => "#", class: "bottom-btn"}
            %i.far.fa-grin-squint#squint
          = link_to "マイページ", user_path(:id), class: "bottom-box_my-page--btn"
      - else
        .adjustment-box
        .bottom-box_registration
          = link_to "無料会員登録", new_user_path, method: :get, class: "bottom-box_registration--btn"
        = link_to "ログイン", user_session_path, method: :post, class: "bottom-box_login"
        

app/views/credit_cards/_side-bar.html.haml
.contents__body__side
  .contents__body__side--1
    .heading
      %p.menu マイページメニュー
    .box
      = link_to information_users_path , class: "link-btn" do
        %p.link-letter お知らせ
    .box
      = link_to favoriteGoods_user_path(:id) , class: "link-btn" do
        %p.link-letter いいねした商品
  .contents__body__side--2
    .heading
      %p.menu 商品を出品する
    .box
      = link_to new_item_path , class: "link-btn" do
        %p.link-letter 商品を出品する
    .box
      = link_to exhibitedShow_user_path(:id) , class: "link-btn" do
        %p.link-letter 出品した商品
    .box
      %p.box__letter 自分のショップを見る
  .contents__body__side--3
    .heading
      %p.menu 商品を購入する
    .box
      = link_to purchaseGoods_user_path(:id) , class: "link-btn" do
        %p.link-letter 購入した商品
    .box
      %p.box__letter 最近見た商品
    .box
      = link_to commentGoods_user_path(:id) , class: "link-btn" do
        %p.link-letter コメントした商品
  .contents__body__side--4
    .heading
      %p.menu その他
    .box
      = link_to setUpShow_users_path , class: "link-btn" do
        %p.link-letter 設定
    .box
      = link_to "#" , class: "link-btn" do
        %p.link-letter お問い合わせ
    .box
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "box__logout"

app/views/credit_cards/new.html.haml
.contents
  = render "header-top"
  .contents__body
    = render "side-bar"
    .creditNew
      %p.creditNew--Title クレジットカード情報入力
      = render "flash-messages"
      .creditNew--list
        = form_tag(credit_cards_path, method: :post, id: 'charge-form',  name: "inputForm") do
          .fields
            %p.letter--1 カード番号
            %p.letter--2 ※必須
          %p.Form-mge <半角英数字で入力してください>  <12文字迄>
          = text_field_tag "number", "", class: "number", placeholder: "例) 1234123412341234（ハイフンなし）" ,maxlength: "16", type: "text", id: "card_number"
          %br
          .box-text
            %p.letter--1 有効期限
            %p.letter--2 ※必須
          %p.Form-mge <下記から選択してください> 
          .box-fields
            .field
              %select#exp_month{name: "exp_month", type: "text"}
                %option{value: ""} --
                %option{value: "1"}01
                %option{value: "2"}02
                %option{value: "3"}03
                %option{value: "4"}04
                %option{value: "5"}05
                %option{value: "6"}06
                %option{value: "7"}07
                %option{value: "8"}08
                %option{value: "9"}09
                %option{value: "10"}10
                %option{value: "11"}11
                %option{value: "12"}12
              %span.day 月
            .field
              %select#exp_year{name: "exp_year", type: "text"}
                %option{value: ""} --
                %option{value: "2019"}19
                %option{value: "2020"}20
                %option{value: "2021"}21
                %option{value: "2022"}22
                %option{value: "2023"}23
                %option{value: "2024"}24
                %option{value: "2025"}25
                %option{value: "2026"}26
                %option{value: "2027"}27
                %option{value: "2028"}28
                %option{value: "2029"}29
              %span.day 年
          %br
          .fields-c
            %p.letter--1 セキュリティコード
            %p.letter--2 ※必須
          %p.Form-mge-c <半角英数字で入力してください>
          = text_field_tag "cvc", "", class: "cvc", placeholder: "カード背面3桁もしくは4桁の番号", maxlength: "4", id: "cvc"
          #card_token
            = submit_tag "追加する", id: "token_submit"
          = link_to "もどる", user_path(:id), class: "back-btn"

  .contents__box
  .footer
  = render "footer-bottom"

app/views/credit_cards/show.html.haml
.contents
  = render "header-top"
  .contents__body
    = render "side-bar"
    .creditShow
      %p.creditShow--Title 登録クレジットカード情報
      .creditShow--list
        %p.numbers_title カード番号
        .numbers_info
          = "**** **** **** " + @default_card_information.last4
        %br
        %p.date_title 有効期限
        .date_info
          - exp_month = @default_card_information.exp_month.to_s
          - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
          = exp_month + " / " + exp_year
        = link_to '削除する', credit_card_path, method: :delete, class: "destroy-btn"
        = link_to "もどる", user_path(:id), class: "back-btn"
  .contents__box
  .footer
  = render "footer-bottom"