config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations', sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'items#index'
  resources :items do
    resources :comments, only: :create
    resources :favorites, only: [:create, :destroy]

    collection do
      get 'category/get_category_children', to: 'items#get_category_children', defaults: { format: 'json' }
      get 'list'
      get 'search'
      get 'detail_search'
    end
    member do
      get 'purchase'
      post 'pay'
    end
  end

  resources :users do
    member do #idを指定して特定のページにいく必要がある
      get 'exhibitedShow'
      get 'purchaseGoods'
      get 'commentGoods'
      get 'favoriteGoods'
    end
    collection do #idを指定して特定のページにいく必要がない
      get 'setUpShow'
      get 'information'
    end
  end

  resources :addresses, only: [:new, :create, :edit, :update]
  resources :credit_cards, only:[:index, :new, :create, :destroy, :show]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable,
        :omniauthable, omniauth_providers: [:facebook, :google_oauth2]
  
  has_many :items
  has_many :comments
  has_one :address, dependent: :destroy
  has_one :credit_card, dependent: :destroy
  has_many :sns_credentials
  has_many :favorites, dependent: :destroy
  has_many :items, through: :favorites

  def self.from_omniauth(auth)
    sns = SnsCredential.where(provider: auth.provider, uid: auth.uid).first_or_create
    # sns認証したことがあればアソシエーションで取得
    # 無ければemailでユーザー検索して取得orビルド(保存はしない)
    user = sns.user || User.where(email: auth.info.email).first_or_initialize(
      nickname: auth.info.name,
        email: auth.info.email
    )
    # userが登録済みの場合はそのままログインの処理へ行くので、ここでsnsのuser_idを更新しておく
    if user.persisted?
      sns.user = user
      sns.save
    end
    user
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end

  def facebook
    authorization
  end

  def google_oauth2
    authorization
  end

  def failure
    redirect_to root_path
  end

  private

  def authorization
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted? #ユーザー情報が登録済みなので、新規登録ではなくログイン処理を行う
      sign_in_and_redirect @user, event: :authentication
    else #ユーザー情報が未登録なので、新規登録画面へ遷移する
      render template: 'devise/registrations/new'
    end
  end
  
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  prepend_before_action :check_captcha, only: [:create]
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  private
  def check_captcha
    unless verify_recaptcha(message: "reCAPTCHAのチェックをしてください")
      self.resource = resource_class.new sign_up_params
      resource.validate # Look for any other validation errors besides reCAPTCHA
      set_minimum_password_length
      respond_with_navigational(resource) { render :new }
    end 
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  prepend_before_action :check_captcha, only: [:create] # Change this to be any actions you want to protect.
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  private
    def check_captcha
      unless verify_recaptcha
        self.resource = resource_class.new sign_in_params
        respond_with_navigational(resource) { render :new }
      end 
    end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  

  def new
  end
  
  # def create
  #   @user = User.create(user_registration_params)
  #   @nickname = current_user.nickname
  # end
  


  def show
    @items = Item.all
    @nickname = current_user.nickname
  end

  def exhibitedShow
    @items = Item.all
    @nickname = current_user.nickname
    
  end

  def setUpShow
    @address = current_user.address
  end

  def purchaseGoods
    @items = Item.all
    # @buyer = Item.where(buyer_id:current_user.id)
  end

  def commentGoods
    @items = Item.all
    @comments = Comment.all
  end

  def favoriteGoods
    @items = Item.all
    @favorites = Favorite.all
  end

  def information
    
  end

  
  # private
  # def user_registration_params
  #   params.require(:user).permit(:nickname, :family_name, :first_name, :family_name_kana, :first_name_kana)
  # end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_header-top.html.haml
.contents__top
  .top-title
    %p Rider’s Garage
  .top-text 
    %p アプリをダウンロードして、バイクパーツ・ウェアを売買しよう。
.contents__header
  .header--box
  .header--logo
    = link_to root_path, class: "logo-link" do
      =image_tag(asset_path('14309.gif'), width:"360", height:"180",class: "logo-pte")
      %p.logo-name Rider’s Garage
      %p.logo-text フリマアプリ&サイト Rider’s Garage[ライダースーガレッジ]
  .header--search
    .search-box
      = form_with(url: search_items_path, local: true, method: :get, class: "search-form") do |f|
        = f.text_field :keyword, placeholder: "検索する", class: "search-input"
        %label{for: "search-icon", class: "search-label"}
          %i.fas.fa-search
        .search-icon
          = f.submit "検索", class: "search-btn", id: "search-icon"
    .login
      - if user_signed_in?
        .adjustment-box
        .bottom-box_notice
          %a{:href => "#", class: "bottom-btn"}
            %i.far.fa-bell#bell
          = link_to "お知らせ", information_users_path, class: "bottom-box_notice--btn", id: "search"
        .bottom-box_my-page
          %a{:href => "#", class: "bottom-btn"}
            %i.far.fa-grin-squint#squint
          = link_to "マイページ", user_path(:id), class: "bottom-box_my-page--btn"
      - else
        .adjustment-box
        .bottom-box_registration
          = link_to "無料会員登録", new_user_path, method: :get, class: "bottom-box_registration--btn"
        = link_to "ログイン", user_session_path, method: :post, class: "bottom-box_login"
        

app/views/users/_side-bar.html.haml
.contents__body__side
  .contents__body__side--1
    .heading
      %p.menu マイページメニュー
    .box
      = link_to information_users_path , class: "link-btn" do
        %p.link-letter お知らせ
    .box
      = link_to favoriteGoods_user_path(:id) , class: "link-btn" do
        %p.link-letter いいねした商品
  .contents__body__side--2
    .heading
      %p.menu 商品を出品する
    .box
      = link_to new_item_path , class: "link-btn" do
        %p.link-letter 商品を出品する
    .box
      = link_to exhibitedShow_user_path(:id) , class: "link-btn" do
        %p.link-letter 出品した商品
    .box
      %p.box__letter 自分のショップを見る
  .contents__body__side--3
    .heading
      %p.menu 商品を購入する
    .box
      = link_to purchaseGoods_user_path(:id) , class: "link-btn" do
        %p.link-letter 購入した商品
    .box
      %p.box__letter 最近見た商品
    .box
      = link_to commentGoods_user_path(:id) , class: "link-btn" do
        %p.link-letter コメントした商品
  .contents__body__side--4
    .heading
      %p.menu その他
    .box
      = link_to setUpShow_users_path , class: "link-btn" do
        %p.link-letter 設定
    .box
      = link_to "#" , class: "link-btn" do
        %p.link-letter お問い合わせ
    .box
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "box__logout"

app/views/users/commentGoods.html.haml
.contents
  = render "header-top"
  .contents__body
    = render "side-bar"
    .exhibited-list
      %p.exhibitedText コメントした商品
      .exhibitedHeading
        %p.exhibitedHeading--title コメントした商品一覧
      .exhibitedGoods
        - @comments.each do |comment|
          - @items.each do |item,i|
            - if current_user.id == comment.user_id
              - if item.id == comment.item_id
                - if item.images.present?
                  .exhibitedGoods__box
                    .exhibitedGoods--image
                      %a{:href => item_path(item.id)}
                        = image_tag (item.images[0].item_image.url), size: "205x230"
                    .exhibitedGoods--details{"data-index" => "#{i}"}
                      %a{:href => item_path(item.id), class: "exhibitedGoods--link"}
                        .text_field
                          .iName
                            = "#{item.name}"
                          .iPrice
                            = "¥#{item.price}"
  .contents__box
  .footer
    = render "footer-bottom"

app/views/users/exhibitedShow.html.haml
.contents
  = render "header-top"
  .contents__body
    = render "side-bar"
    .exhibited-list
      %p.exhibitedText 出品した商品
      .exhibitedHeading
        %p.exhibitedHeading--title 出品した商品一覧
      .exhibitedGoods
        - @items.each do |item,i|
          - if item.user_id == current_user.id
            - if item.images.present?
              .exhibitedGoods__box
                .exhibitedGoods--image
                  %a{:href => item_path(item.id)}
                    = image_tag (item.images[0].item_image.url), size: "205x230"
                .exhibitedGoods--details{"data-index" => "#{i}"}
                  %a{:href => item_path(item.id), class: "exhibitedGoods--link"}
                    .text_field
                      .iName
                        = "#{item.name}"
                      .iPrice
                        = "¥#{item.price}"
                  .btn-field
                    = link_to "編集", "#", class: "link-btn1", data: {"turbolinks" => false}
                    = link_to '削除', "/items/#{item.id}", class: "link-btn2", method: :delete
  .contents__box
  .footer
    = render "footer-bottom"

app/views/users/favoriteGoods.html.haml
.contents
  = render "header-top"
  .contents__body
    = render "side-bar"
    .exhibited-list
      %p.exhibitedText いいねした商品
      .exhibitedHeading
        %p.exhibitedHeading--title いいねした商品一覧
      .exhibitedGoods
        - @favorites.each do |favorite|
          - @items.each do |item,i|
            - if current_user.id == favorite.user_id
              - if item.id == favorite.item_id
                - if item.images.present?
                  .exhibitedGoods__box
                    .exhibitedGoods--image
                      %a{:href => item_path(item.id)}
                        = image_tag (item.images[0].item_image.url), size: "205x230"
                    .exhibitedGoods--details{"data-index" => "#{i}"}
                      %a{:href => item_path(item.id), class: "exhibitedGoods--link"}
                        .text_field
                          .iName
                            = "#{item.name}"
                          .iPrice
                            = "¥#{item.price}"
  .contents__box
  .footer
    = render "footer-bottom"

app/views/users/information.html.haml
.contents
  = render "header-top"
  .contents__body
    = render "side-bar"

  .contents__box
  .footer
    = render "footer-bottom"

app/views/users/new.html.haml
.contents
  .contents__top
    .top-title
      %p Rider’s Garage
    .top-text 
  .contents-middle
    %p.middle-text 新規会員登録
    .middle-separator
  .contents-box
    .contents-header
      .contents-header--box
      .contents-header--logo
        = link_to root_path, class: "contents-header--logo--link" do
          =image_tag asset_path('14309.gif'), width:"400", height:"220",class: "logo-pte"
          %p.logo-name Rider’s Garage
          %p.logo-text フリマアプリ&サイト<br>Rider’s Garage[ライダースーガレッジ]
      .contents-header--section
        .section--box
          %p.section-text-a お持ちのメールアドレスで登録
          = link_to new_user_registration_path, class: "btn-mail" do
            = icon('far', 'envelope', class: "icon")
            メールアドレスで登録する
          %p.section-text-b SNSアカウントで登録/お持ちのアカウントで登録
          = link_to user_google_oauth2_omniauth_authorize_path, method: :post, class: "btn-GG" do
            = icon('fab', 'google', class: "icon")
            Googleで登録する
          = link_to user_facebook_omniauth_authorize_path, method: :post, class: "btn-FB" do
            = icon('fab', 'facebook-square', class: "icon")
            Facebookで登録する
          = link_to "#", class: "btn-Ap" do
            = icon('fab', 'twitter', class: "icon")
            Twitterで登録する
          %a.top-backBtn{:href => "/items"} トップページに戻る
          .Text
            登録することで、利用規約とプライバシーポリシーに同意したものとみなされます。

app/views/users/purchaseGoods.html.haml
.contents
  = render "header-top"
  .contents__body
    = render "side-bar"
    .exhibited-list
      %p.exhibitedText 購入した商品
      .exhibitedHeading
        %p.exhibitedHeading--title 購入した商品一覧
      .exhibitedGoods
        - @items.each do |item,i|
          -if current_user.id == item.buyer_id
            - if item.images.present?
              .exhibitedGoods__box
                .exhibitedGoods--image
                  %a{:href => item_path(item.id)}
                    = image_tag (item.images[0].item_image.url), size: "205x230"
                .exhibitedGoods--details{"data-index" => "#{i}"}
                  %a{:href => item_path(item.id), class: "exhibitedGoods--link"}
                    .text_field
                      .iName
                        = "#{item.name}"
                      .iPrice
                        = "¥#{item.price}"
          
  .contents__box
  .footer
    = render "footer-bottom"

app/views/users/setUpShow.html.haml
.contents
  = render "header-top"
  .contents__body
    = render "side-bar"
    .setUp-list
      %p.setUp-Title 設定
      .setUp-content
        .setUpHeading
          %p.setUpHeading--title ユーザー情報
        .setUpMenu
          = link_to new_address_path , class: "menu-btn" do
            .menu
              %p.menu-text1 連絡先・住所の設定
              %p.menu-text2 配送先の住所や電話番号などの情報
        .setUpMenu
          = link_to new_credit_card_path , class: "menu-btn" do
            .menu
              %p.menu-text1 支払い方法登録
              %p.menu-text2 クレジットカード情報入力
        .setUpMenu-last
          = link_to destroy_user_session_path , class: "menu-btn" do
            .menu
              %p.menu-text1 ログアウト
              %p.menu-text2 Rider’s Garageからログアウトします
      
      .setUp-content2
        .setUpHeading2
          %p.setUpHeading2--title2 登録情報の変更・削除
        .setUpMenu2
          = link_to edit_address_path(:id) , class: "menu-btn2" do
            .menu
              %p.menu-text1 発送元・お届け先住所変更
              %p.menu-text2 登録した住所や電話番号などの情報変更
        .setUpMenu2
          = link_to credit_card_path(:id),  class: "menu-btn2" do
            .menu
              %p.menu-text1 支払い方法確認
              %p.menu-text2 クレジットカード情報確認
        .setUpMenu-last
          = link_to edit_user_registration_path , class: "menu-btn2" do
            .menu
              %p.menu-text1 ログイン情報の変更
              %p.menu-text2 登録したメール/パスワード、氏名の情報変更
      .setUp-content3
        .setUpHeading3
          %p.setUpHeading3--title3 登録情報の変更
        .setUpMenu3
          = link_to "#" , class: "menu-btn3" do
            %p.menu-text1 退会申請
            %p.menu-text2 Rider’s Garageから退会申請します
  .contents__box
  .footer
    = render "footer-bottom"
    

app/views/users/show.html.haml
.contents
  = render "header-top"
  .contents__body
    = render "side-bar"
    .show-contents
      %p.showTitle
        = "#{@nickname}さんのマイページ"
      = render "flash-messages"
  .contents__box
  .footer
  = render "footer-bottom"