config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations', sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'items#index'
  resources :items do
    resources :comments, only: :create
    resources :favorites, only: [:create, :destroy]

    collection do
      get 'category/get_category_children', to: 'items#get_category_children', defaults: { format: 'json' }
      get 'list'
      get 'search'
      get 'detail_search'
    end
    member do
      get 'purchase'
      post 'pay'
    end
  end

  resources :users do
    member do #idを指定して特定のページにいく必要がある
      get 'exhibitedShow'
      get 'purchaseGoods'
      get 'commentGoods'
      get 'favoriteGoods'
    end
    collection do #idを指定して特定のページにいく必要がない
      get 'setUpShow'
      get 'information'
    end
  end

  resources :addresses, only: [:new, :create, :edit, :update]
  resources :credit_cards, only:[:index, :new, :create, :destroy, :show]
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true
  belongs_to :category
  belongs_to :user, optional: true #外部キーのnilを許可する
  has_many :comments
  
  has_many :favorites, dependent: :destroy
  has_many :users, through: :favorites


  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :shipping_date
  belongs_to_active_hash :prefecture
  belongs_to_active_hash :delivery_fee
  belongs_to_active_hash :status

  def self.search(search)
    return Item.all unless search
    Item.where('name LIKE(?)', "%#{search}%")
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_ransack, only: [:list, :search, :detail_search]

  def index
    @items = Item.includes(:images).order('created_at DESC') #トップページに表示、更新した順番で
    @parents = Category.where(ancestry: nil)
  end

  def new
    @item = Item.new
    @item.images.new

    #セレクトボックスの初期値設定
    @category_parent_array = ["---"]
    #データベースから、親カテゴリーのみ抽出し、配列化
    @category_parent_array = Category.where(ancestry: nil)

  end

  # 以下全て、formatはjsonのみ
  # 親カテゴリーが選択された後に動くアクション
  def get_category_children
    #選択された親カテゴリーに紐付く子カテゴリーの配列を取得
    @category_children = Category.find(params[:parent_id]).children
  end


  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to user_path(:id), notice: "Product listing completed！"
    else
      render :new
    end
  end

  def edit
    @item = Item.find(params[:id])
    @item.edit
    redirect_to root_path
  end


  def show
    @item = Item.find(params[:id])
    @parents = Category.where(ancestry: nil)
    @category = Category.find(@item.category_id)
    @user = User.find(@item.user_id)
    @comment = Comment.new
    @comments = @item.comments.includes(:user)
    
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to root_path
  end


  def purchase
    @family_name = current_user.family_name
    @first_name = current_user.first_name
    @item = Item.find(params[:id])
    @card = CreditCard.find_by(user_id: current_user.id)
    Payjp.api_key = ENV['PAYJP_PRIVATE_KEY']
    if @card.blank?
      flash[:alert] = 'Please register your card！'
      redirect_to user_path(:id) and return
    else
      @customer = Payjp::Customer.retrieve(@card.customer_id)
      @customer_card = @customer.cards.retrieve(@card.card_id)
    end

    if current_user.address.present?
      @address = current_user.address
    else
      flash[:alert] = "Please register your address！"
      redirect_to user_path(:id)
    end
  end


  def pay
    @item = Item.find(params[:id])
    @card = CreditCard.find_by(user_id: current_user.id)
    Payjp.api_key = ENV['PAYJP_PRIVATE_KEY']
    
    charge = Payjp::Charge.create(
      :amount => @item.price,
      :customer => @card.customer_id,
      :currency => 'jpy',
    )

    @item.update(buyer_id: current_user.id)
    redirect_to user_path(:id), notice: 'Purchase of the product is completed！'
  end

  def list
    @items = Item.where(category_id: params[:category_id])
    @parents = Category.where(ancestry: nil)
    
    @item = Item.find_by(category_id: params[:category_id])
    if @item.present?
      @category = Category.find(@item.category_id)
    end
  end

  def search
    @items = Item.search(params[:keyword])
    @keyword = params[:keyword]
    @parents = Category.where(ancestry: nil)
  end

  def detail_search
    @items = @q.result(distinct: true)
    @parents = Category.where(ancestry: nil)
  end

  private

  def item_params
    params.require(:item).permit(:name, :price, :prefecture_id, :category_id, :shipping_date_id , :delivery_fee_id, :buyer_id, :status_id, :introduction, :brand, images_attributes: [:item_image, :_destroy, :id]).merge(user_id: current_user.id)
  end

  def set_ransack
    @q = Item.ransack(params[:q])
  end
  
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_category-list.html.haml
.categories
  .categories--contents
    .categories--title カテゴリから探す
    %ul.category__parent
      - @parents.each do |parent|
        .category-box{id: "parent_category#{parent.id}"}
          %p.parent_category{id: "parent#{parent.id}"}
            = "#{parent.name}"
          %i.fas.fa-angle-down
        %ul.category__child{id: "parent_list#{parent.id}"}
          - parent.children.each do |child|
            .category-box{id: "parent_category#{child.id}"}
              = link_to "#{child.name}", list_items_path(category_id:child.id), class: "parent_category",id: "child#{child.id}"
              %i.fas.fa-angle-right
        .paragraph

app/views/items/_footer-top.html.haml
.footer-top
  %p.text-mge Rider's Garageの機能
  .footer-separator
  .FeatureBox
    .Feature1
      .Feature1-a
        .Feature1-a--box
          %p 1.
        .Feature1-a--boxes
          %p.Feature1-a--boxes--text 出品手数料
          %p.Feature1-a--boxes--texts 無料！
      .Feature1-b
        = image_tag(asset_path('6e1bf9.jpg'), width:"400", width:"300", height:"250", class: "Feature1-b--image")
      %p.Feature1-c オークションと違って出品手数料無料！<br>会員登録、月会費などその他の費用も<br>かかりません。
    .Feature2
      .Feature2-a
        .Feature2-a--box
          %p 2.
        .Featur2-a--boxes
          %p.Feature2-a--boxes--text
          %p.Feature2-a--boxes--texts
      .Feature2-b
        %img{:src => "/assets/sdfdefdd.jpeg", width:"300", height:"250", class: "Feature2-b--image"}/
      %p.Feature2-c 最大3%でお得に出品&購入！
    .Feature3
      .Feature3-a
        .Feature3-a--box
          %p 3.
        .Featur3-a--boxes
          %p.Feature3-a--boxes--text シンプル
          %p.Feature3-a--boxes--texts で使いやすい！
      .Feature3-b
        %img{:src => "/assets/name.jpg", width:"300", height:"250", class: "Feature3-b--image"}/
      %p.Feature3-c 商品代金を一度Rider’s Garageが<br>お預かりし、取引が完了したら出品者に<br>お渡しする仕組みです。

app/views/items/_header-top.html.haml
.contents__top
  .top-title
    %p Rider’s Garage
  .top-text 
    %p アプリをダウンロードして、バイクパーツ・ウェアを売買しよう。
.contents__header
  .header--box
  .header--logo
    = link_to root_path, class: "logo-link" do
      =image_tag(asset_path('14309.gif'), width:"360", height:"180",class: "logo-pte")
      %p.logo-name Rider’s Garage
      %p.logo-text フリマアプリ&サイト Rider’s Garage[ライダースーガレッジ]
  .header--search
    .search-box
      = form_with(url: search_items_path, local: true, method: :get, class: "search-form") do |f|
        = f.text_field :keyword, placeholder: "検索する", class: "search-input"
        %label{for: "search-icon", class: "search-label"}
          %i.fas.fa-search
        .search-icon
          = f.submit "検索", class: "search-btn", id: "search-icon"
    .login
      - if user_signed_in?
        .adjustment-box
        .bottom-box_notice
          %a{:href => "#", class: "bottom-btn"}
            %i.far.fa-bell#bell
          = link_to "お知らせ", information_users_path, class: "bottom-box_notice--btn", id: "search"
        .bottom-box_my-page
          %a{:href => "#", class: "bottom-btn"}
            %i.far.fa-grin-squint#squint
          = link_to "マイページ", user_path(:id), class: "bottom-box_my-page--btn"
      - else
        .adjustment-box
        .bottom-box_registration
          = link_to "無料会員登録", new_user_path, method: :get, class: "bottom-box_registration--btn"
        = link_to "ログイン", user_session_path, method: :post, class: "bottom-box_login"
        

app/views/items/_posts-btn.html.haml
= link_to new_item_path do
  .posts-btn
    %span.posts-btn__text 出品する
    = image_tag src="/assets/icon_camera.png", class: "posts-btn__icon"
    

app/views/items/_side-bar.html.haml
.contents__body__side
  .contents__body__side--1
    .heading
      %p.menu マイページメニュー
    .box
      = link_to information_users_path , class: "link-btn" do
        %p.link-letter お知らせ
    .box
      = link_to favoriteGoods_user_path(:id) , class: "link-btn" do
        %p.link-letter いいねした商品
  .contents__body__side--2
    .heading
      %p.menu 商品を出品する
    .box
      = link_to new_item_path , class: "link-btn" do
        %p.link-letter 商品を出品する
    .box
      = link_to exhibitedShow_user_path(:id) , class: "link-btn" do
        %p.link-letter 出品した商品
    .box
      %p.box__letter 自分のショップを見る
  .contents__body__side--3
    .heading
      %p.menu 商品を購入する
    .box
      = link_to purchaseGoods_user_path(:id) , class: "link-btn" do
        %p.link-letter 購入した商品
    .box
      %p.box__letter 最近見た商品
    .box
      = link_to commentGoods_user_path(:id) , class: "link-btn" do
        %p.link-letter コメントした商品
  .contents__body__side--4
    .heading
      %p.menu その他
    .box
      = link_to setUpShow_users_path , class: "link-btn" do
        %p.link-letter 設定
    .box
      = link_to "#" , class: "link-btn" do
        %p.link-letter お問い合わせ
    .box
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "box__logout"

app/views/items/_side-category-list.html.haml
.box
  %i.fas.fa-list-ul
  %p.side-category カテゴリから探す
%ul.category__parent
  - @parents.each do |parent|
    .category-box{id: "category#{parent.id}"}
      %p.parent_category{id: "parent#{parent.id}"}
        = "#{parent.name}"
      %i.fas.fa-angle-down
    %ul.category__child{id: "list#{parent.id}"}
      - parent.children.each do |child|
        .category-box{id: "category#{child.id}"}
          = link_to "#{child.name}", list_items_path(category_id:child.id), class: "parent_category",id: "child#{child.id}"
          %i.fas.fa-angle-right

app/views/items/_side-category_search.html.haml
-# SCSSは、items.list.scssに記載
.box
  %i.fas.fa-list-ul
  %p.side-category カテゴリから探す
%ul.category__parent
  - @parents.each do |parent|
    .category-box{id: "category#{parent.id}"}
      %p.parent_category{id: "parent#{parent.id}"}
        = "#{parent.name}"
      %i.fas.fa-angle-down
    %ul.category__child{id: "list#{parent.id}"}
      - parent.children.each do |child|
        .category-box{id: "category#{child.id}"}
          = link_to "#{child.name}", list_items_path(category_id:child.id), class: "parent_category",id: "child#{child.id}"
          %i.fas.fa-angle-right

app/views/items/_side-detail_search.html.haml
-# SCSSは、side.search.scssに記載
.title-box
  %p.title 詳細検索
.detail_search--box
  = search_form_for(@q,url: detail_search_items_path) do |f|
    .detail-keyword
      .detail-keyword--box
        %i.fas.fa-plus
        %p.wd キーワードを追加する
      = f.search_field :name_cont, placeholder: "例）バイク", class: "detail-keyword--form"
    .detail-price
      .detail-price--label
        %i.fas.fa-coins
        %p.wd 価格
      .detail-price--forms
        = f.search_field :price_gteq, placeholder: "¥300以上", min:300, class: "price-min"
        %p.wd 〜
        = f.search_field :price_lteq, placeholder: "¥9999999以下", max:9999999, class: "price-max"
    .detail-status
      .detail-status--label
        %i.fas.fa-paperclip
        %p.wd 商品の状態
      .detail-status--checkbox
        .checkboxes
          = f.check_box :status_id_eq_any, { multiple: true }, 1, ''
          = '新品、未使用'
        .checkboxes
          = f.check_box :status_id_eq_any, { multiple: true }, 2, ''
          = '未使用に近い'
        .checkboxes
          = f.check_box :status_id_eq_any, { multiple: true }, 3, ''
          = '目立った傷や汚れなし'
        .checkboxes
          = f.check_box :status_id_eq_any, { multiple: true }, 4, ''
          = 'やや傷や汚れあり'
        .checkboxes
          = f.check_box :status_id_eq_any, { multiple: true }, 5, ''
          = '傷や汚れあり'
        .checkboxes
          = f.check_box :status_id_eq_any, { multiple: true }, 6, ''
          = '全体的に状態が悪い'
    .detail-deliveryFee
      .detail-deliveryFee--label
        %i.fas.fa-truck
        %p.wd 配送料の負担
      .detail-deliveryFee--checkbox
        .checkboxes
          = f.check_box :delivery_fee_id_eq_any, { multiple: true }, 1, ''
          = '送料込み(出品者負担)'
        .checkboxes
          = f.check_box :delivery_fee_id_eq_any, { multiple: true }, 2, ''
          = '着払い(購入者負担)'
    .detail-btn
      = f.submit "検索", class: "sbt-btn"

app/views/items/detail_search.html.haml
.contents
  = render "header-top"
.contents__body
  .contents__body--side
    .category_search
      = render "side-category_search"
    .detail_search
      = render "side-detail_search"
  .contents__body--list
    %p.search-result
      ="1-#{@items.count}件表示"
    .listGoods
      - @items.each do |item,i|
        - if item.images.present?
          .listGoods__box
            .listGoods--image
              %a{:href => item_path(item.id)}
                = image_tag (item.images[0].item_image.url), size: "205x230", class: "image-list"
            .listGoods--details{"data-index" => "#{i}"}
              %a{:href => item_path(item.id), class: "listGoods--link"}
                .text_field
                  .iName
                    = "#{item.name}"
                  .iPrice
                    = "¥#{item.price}"
.contents__box
.footer
  = render "footer-bottom"

app/views/items/index.html.haml
.contents
  = render "header-top"
  .contents-body-index
    .body-index
      .body-index--box#slide
        = image_tag asset_path('d18b0b470e4.jpg'), width:"1790", height:"387"
        = image_tag(image_path('material/big_main.jpg'), width:"1790", height:"387")
        = image_tag(image_path('material/shopimg-1.jpg'), width:"1790", height:"387")

    .body-message
      .message__box
        .message__box--from
        .message__box--text
          %p.text-mag バイクパーツ・ウェアを売買できるフリマアプリ
          %p.text-mag1 Rider’s Garageならスマホで写真を撮ってすぐ出品！
          %p.text-mag2 毎日格安商品を見つけよう！アプリをDLしよう！
          .icons
            .apple-icon
              %a{:href => "https://itunes.apple.com/jp/app/instagram/id389801252?mt=8"}
                %img{:alt => "AppStoreで入手", :height => "50", :src => "https://linkmaker.itunes.apple.com/assets/shared/badges/ja-jp/appstore-lrg.svg"}/
            .google-icon
              = image_tag(image_path('material/google-play-badge.png'), width:"200", height:"75")
      .message-image
        = image_tag(image_path('material/smartphone_img01.jpg'), width:"400", height:"275", class: "message-image--pic")
  .contents-items
    %p{:style => "font-size: 20px; font-weight: bold;"} 新着アイテム
    .items-separator
    .itemsNew
      - @items.each_with_index do |item,i|
        - if item.buyer_id.present?
          - if item.images.present?
            .itemsNew__content
              .itemsNew__content__box
                .itemsNew__content__box--image
                  %a{:href => item_path(item.id)}
                    = image_tag (item.images[0].item_image.url), size: "205x240"
                  %a{:href => item_path(item.id), class: "itemsNew-link"}
                    .itemsNew_photo__sold
                      .itemsNew_photo__sold__inner
                        SOLD OUT
                
                  
        - else
          - if item.images.present?
            .itemsNew__content
              .itemsNew__content__box
                .itemsNew__content__box--image
                  %a{:href => item_path(item.id)}
                    = image_tag (item.images[0].item_image.url), size: "205x240"
                .itemsNew__content__box--details{"data-index" => "#{i}"}
                  %a{:href => item_path(item.id), class: "itemsNew-link"}
                    .hidden_field
                      .iName
                        = "#{item.name}"
                      .iPrice
                        = "¥#{item.price}"
  .category-contents
    = render "category-list"
  .footer
    = render "footer-top"
    = render "footer-bottom"
-if user_signed_in?
  .btn
    = render "posts-btn"

app/views/items/list.html.haml
.contents
  = render "header-top"
.contents__body
  .contents__body--side
    .category_search
      = render "side-category_search"
    .detail_search
      = render "side-detail_search"
  .contents__body--list
    -if @items.present?
      %p.categoryName
        = "#{@category.name}の商品一覧"
      %ul.lists
        %li.listList
          = link_to "Rider’s Garage", root_path, class: "listList--link"
          %i.fas.fa-greater-than
        %li.listList
          %p.listList--link
            = @category.parent.name
          %i.fas.fa-greater-than
        %li.listList
          %p.listList--link
            = @category.name
      .listGoods
        - @items.each do |item,i|
          - if item.images.present?
            .listGoods__box
              .listGoods--image
                %a{:href => item_path(item.id)}
                  = image_tag (item.images[0].item_image.url), size: "205x230", class: "image-list"
              .listGoods--details{"data-index" => "#{i}"}
                %a{:href => item_path(item.id), class: "listGoods--link"}
                  .text_field
                    .iName
                      = "#{item.name}"
                    .iPrice
                      = "¥#{item.price}"
    -else
      .notice_text 該当商品が見つかりません
-# -if @items.present?
-#   .neck
-# - else
-#   .another-neck

.footer
  = render "footer-bottom"

app/views/items/new.html.haml
.contents
  = render "header-top"
  .contents__body
    = render "side-bar"
    .contents__body__input-list
      = form_with(model: @item, url: items_path, local: true, class: "contents__body__input-list__form") do |f|

        .input-list__image
          .input-list_images
            .input-list__image-1#image-boxer
              %label{for: "file-sample"}
                %i.fas.fa-camera#image-icon
            .input-list__image-2
              = f.fields_for :images do |i|
                .input-field{"data-index" => "#{i.index}"}
                  = i.file_field :item_image, type: 'file', id: "file-sample"
          .input-list_images
            .input-list__image-1#image-boxer1
              %label{for: "file-sample1"}
                %i.fas.fa-camera#image-icon
            .input-list__image-2
              = f.fields_for :images do |i|
                .input-field{"data-index" => "#{i.index}"}
                  = i.file_field :item_image, type: 'file', id: "file-sample1"
          .input-list_images
            .input-list__image-1#image-boxer2
              %label{for: "file-sample2"}
                %i.fas.fa-camera#image-icon
            .input-list__image-2
              = f.fields_for :images do |i|
                .input-field{"data-index" => "#{i.index}"}
                  = i.file_field :item_image, type: 'file', id: "file-sample2"
          .input-list_images
            .input-list__image-1#image-boxer3
              %label{for: "file-sample3"}
                %i.fas.fa-camera#image-icon
            .input-list__image-2
              = f.fields_for :images do |i|
                .input-field{"data-index" => "#{i.index}"}
                  = i.file_field :item_image, type: 'file', id: "file-sample3"

        .product-name
          %p.letter--1 商品名
          %p.letter--2 ※必須
          = f.text_field :name, placeholder: "商品名（必須 40文字まで)", class: "form--text"
        
        .introduction
          %p.introduction--letter1 商品説明
          %p.introduction--letter2 ※必須
          = f.text_area :introduction, placeholder: "商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）", class: "introduction__form-area"
        .form-separator
        
        .status
          %p.letter--1 商品の状態
          %p.letter--2 ※必須
          = f.collection_select :status_id, Status.all, :id, :name
        
        .brand
          %p.letter--1 ブランド名
          %p.letter--3 ※任意
          = f.text_field :brand, placeholder: "例)シャネル", class: "brand--text"

        .category
          %p.letter--1 商品カテゴリ
          %p.letter--2 ※必須
          .category_choose
            = f.collection_select :category_id, Category.where(ancestry: nil), :id, :name, {prompt: '---'}, {id: 'parent_category'}
        .form-separator
        
        .delivery
          %p.letter--1 配送料の負担
          %p.letter--2 ※必須
          = f.collection_select :delivery_fee_id, DeliveryFee.all, :id, :name

        .shipping
          %p.letter--1 発送日の目安
          %p.letter--2 ※必須
          = f.collection_select :shipping_date_id, ShippingDate.all, :id, :name

        .prefecture
          %p.letter--1 発送元の地域
          %p.letter--2 ※必須
          = f.collection_select :prefecture_id, Prefecture.all, :id, :name
        .form-separator

        .price
          %p.letter--1 商品価格
          %p.letter--2 ※必須
          = f.number_field :price, min:300, max:9999999, id: "price_calc", placeholder: "¥300 ~ ¥9999999", value: ""
        .price__charge
          .price__charge--box
          .price__charge--tax 販売手数料（10%）
          %span.price__charge--line{ id: 'sell-main__fee' } ー
        %hr{:color => "#F5F5F5", class:"contents__input-list__form__price__sale__horizontal"}
        .price__profit
          .price__profit--box
          .price__profit--tax 販売利益
          %span.price__profit--line{ id: 'sell-main__profit' } ー

        .form-post
          = f.submit "出品する", class: "form-post--send"
        

app/views/items/search.html.haml
.contents
  = render "header-top"
.contents__body
  .contents__body--side
    .category_search
      = render "side-category_search"
    .detail_search
      = render "side-detail_search"
  .contents__body--list
    -# keyword-titleのSCSSは、items.list.scssに記載
    %p.keyword-title 
      = "#{@keyword} の検索結果"
    .listGoods
      - @items.each do |item,i|
        - if item.images.present?
          .listGoods__box
            .listGoods--image
              %a{:href => item_path(item.id)}
                = image_tag (item.images[0].item_image.url), size: "205x230", class: "image-list"
            .listGoods--details{"data-index" => "#{i}"}
              %a{:href => item_path(item.id), class: "listGoods--link"}
                .text_field
                  .iName
                    = "#{item.name}"
                  .iPrice
                    = "¥#{item.price}"
.contents__box
.footer
  = render "footer-bottom"

app/views/items/show.html.haml
.contents
  = render "header-top"
  .contents-body-show
    .body-showTop
      %ul.lists
        %li.showList
          = link_to "Rider’s Garage", root_path, class: "showList--link"
        %i.fas.fa-greater-than
        %li.showList
          %p.showList--link
            = @category.parent.name
        %i.fas.fa-greater-than
        %li.showList
          = link_to "#" , class: "showList--link" do
            = @category.name
        %i.fas.fa-greater-than
        %li.showList
          = @item.name
    .body-showMde
      .showMde--box
        .showMde--left
          .itemImage--main
            - if @item.buyer_id.present?
              - @item.images.each_with_index do |image, index|
                - if index == 0
                  .itemMain-images{"data-index" => "#{index}"}
                    = image_tag image.item_image.url, :width =>'500px', :height =>'540px', class: "main__image"
                  .itemMain_photo-sold
                    .itemMain_photo-sold__inner
                      SOLD OUT
            - else
              - @item.images.each_with_index do |image, index|
                - if index == 0
                  .itemMain-images{"data-index" => "#{index}"}
                    = image_tag image.item_image.url, :width =>'500px', :height =>'540px', class: "main__image"
              
          .itemImage--sub
            - @item.images.each_with_index do |image, index|
              - if image.persisted?
                .itemSub-images{"data-index" => "#{index}"}
                  = image_tag image.item_image.url, :width =>'115px', :height =>'120px', class: "image__list"
          .itemOption
            .itemFavorite
              - if user_signed_in?
                - if current_user.favorites.find_by(item_id: @item.id)
                  = link_to item_favorite_path(@item), method: :delete, class: "favorited-link" do
                    .favorited-btn
                      %i.fas.fa-heart
                      %p.btn-text いいね
                      .like-counts
                        = "#{@item.favorites.count}件"
                -else
                  = link_to item_favorites_path(@item), method: :post, class: "favorite-link" do
                    .favorite-btn
                      %i.far.fa-heart
                      %p.btn-text いいね
                      .like-counts
                        = "#{@item.favorites.count}件"
              - else
                = link_to user_session_path , method: :post, class: "favorite-link" do
                  .favorite-btn
                    %i.far.fa-heart
                    %p.btn-text いいね
                    .like-counts
                      = "#{@item.favorites.count}件"
            .itemComment
              .comment-counts
                %i.far.fa-comment
                %p.text コメント
                .counts
                  = "#{@item.comments.count}件"

        .showMde--right
          %h1.item-name
            = @item.name
          .item-brand
            = @item.brand
          .item-box
            .item-price
              = "¥#{@item.price}"
            .item-fee
              = @item.delivery_fee.name
          - if user_signed_in?
            -if current_user.id == @item.user_id
              .emptyBox
            -else 
              - if @item.buyer_id.present?
                .emptyBox
              -else 
                %a{:href => purchase_item_path(@item.id), class: "buy-btn--link"}
                  .buy-btn
                    %i.fas.fa-shopping-cart
                    %p.btn-text 購入する
          - else
            .emptyBox
          .item-introduction
            %p.itemExplanation 商品説明
          .item-contents
            = @item.introduction
          .item-list
            .separator
              %span ブランド
              %span.info
                = @item.brand
            .separator
              %span カテゴリ
              %span.info 
                = @category.name
            .separator
              %span 商品の状態
              %span.info 
                = @item.status.name
            .separator
              %span 配送料
              %span.info 
                = @item.delivery_fee.name
            .separator
              %span 発送元の地域
              %span.info 
                = @item.prefecture.name
            .separator-last
              %span 発送日の目安
              %span.info 
                = @item.shipping_date.name
          .exhibitor-name
            %i.far.fa-grin-squint
            %span 出品者
            %span.info 
              = @user.nickname
      .body-showUnder
        %p.showUnder-text この商品について質問
        .underBar
        .comment-list
          - if @comments
            - @comments.each do |comment|
              .comments
                %p
                  = comment.user.nickname
                  %span ：
                  = comment.text
        .comment-box
          %i.fas.fa-exclamation-triangle
          %span.caution 直接取引や個人情報のやり取りは禁止しております。
          = form_with(model: [@item, @comment], class: "comment-box--form", local: true) do |f|
            = f.text_area :text, placeholder: "質問を入力する", class: "comment-area"
            - if user_signed_in?
              = f.submit "質問する", class: "comment-send"
            - else
              %p.login-caution ※ログインすると質問できるようになります。
              = link_to "ログイン", user_session_path, method: :post, class: "comment-box_login"
        %a.backBtn{:href => "/items"} トップページにもどる
  .footer
    = render "footer-bottom"
  
  - if user_signed_in?
    -if current_user.id == @item.user_id
      = render "delete-btn"
    -else 